### PR TITLE
#159987627 Enable Social authentication 

### PR DESCRIPTION
**Pull request by CEOehis**
#### What does this PR do?
Users should be able to Login via Google and Facebook

#### Description of Task to be completed?
- Enable authentication using Google and Facebook
- Include relevant tests

####How should this be manually tested?
- Create a [google](https://console.developers.google.com/) and [facebook](https://developers.facebook.com) developer account. ( The process is a bit involved since you would need to create a new app and adjust the settings for development )
- clone the [backend repo](https://github.com/andela/thor-ah)
- update the `.env` file on the backend with
```
FACEBOOK_APP_ID='id-you-get-from-fb'
FACEBOOK_APP_SECRET='your-facebook-app-secret'
GOOGLE_APP_ID='id-you-get-from-google'
GOOGLE_APP_SECRET='your-google-app-secret'
GOOGLE_CALLBACK_URL=http://localhost:3001/api/auth/google/callback
FACEBOOK_CALLBACK_URL=http://localhost:3001/api/auth/facebook/callback
```

NB: The localhost base url will be the same one your front end is running on

#### What are the relevant pivotal tracker stories?
[#159987627](https://www.pivotaltracker.com/story/show/159987627)

#### Screenshots (if appropriate)
screenshot 2018-10-19 at 5 57 00 pm

### CODE REVIEW

**Review by lauragift21 — APPROVED** [review]
LGTM

**Review by emekafredy — APPROVED** [review]
LGTM. Resolve conflicts and you're good

**Review by d-beloved — APPROVED** [review]
LGTM

**Review by johnkingzy — APPROVED** [review]
LGTM

**Pull request merged**
