### PR TITLE
#159987632 Pagination support for articles display

### PR DESCRIPTION
**Pull request by d-beloved**
#### What does this PR do?

-- Pagination support for ```get all articles``` view

#### Description of Task to be completed?

-- create the pagination component and apply it to the views for rendering article cards

#### How should this be manually tested?

-- Clone the repo from the latest change.
-- Install node.js on your local machine.
-- Clone the backend repo from [here](https://github.com/andela/thor-ah)
-- update the `.env` file on the backend according to the ```.env-sample```
-- Run ```npm install```
-- Run npm run dev.
-- Navigate to the landing page.
-- Click on next page icons

#### What are the relevant pivotal tracker stories?

-- [#159987632](https://www.pivotaltracker.com/story/show/159987632)

### CODE REVIEW

**Review by lauragift21 — APPROVED** [review]
LGTM

**Review by emekafredy — APPROVED** [review]
Cool Stuff

**Review by emekafredy — APPROVED** [review]
Cool stuff

**Review by emekafredy — APPROVED** [review]

**Review by emekafredy — APPROVED** [review]
cool stuff

**Review by emekafredy — APPROVED** [review]
LGTM

**Review by emekafredy — APPROVED** [review]
LGTM

**Review by emekafredy — APPROVED** [review]
Cool stuff

**Review by johnkingzy — APPROVED** [review]
LGTM

**Pull request merged**
