### PR TITLE
#159987621 setup react router for the app

### PR DESCRIPTION
**Pull request by emekafredy**
### What does this PR do?
Setup router for the react app

### Description of Task to be completed?
- install the react-router-dom package
- import the package to setup routing for the pages
- create a dummy sample page and a ‘/‘ to test routing
- define a components and containers file structure

### How should this be manually tested?
- clone the repo
- cd into 'thor-ah-frontend'
- run 'npm install'
- run 'npm start’
- test the router with the available links on the navbar

### What are the relevant pivotal tracker stories?
[159987621](https://www.pivotaltracker.com/story/show/159987621)

### CODE REVIEW

**Review by gonuoha — APPROVED** [review]
LGTM

**Review by iamuchejude — APPROVED** [review]
Good work

**Review by emmaadesile — APPROVED** [review]
LGTM

**Review by johnkingzy — APPROVED** [review]
Looks Good 👍

**Pull request merged**
